### PR TITLE
Change to using inline array annotation for dependency injection. 

### LINKED ISSUE #1: Can't use angular-ra-newrelic with atomify/browserify + minifiy
I am using angular-ra-newrelic within a project that uses [Atomify](https://github.com/atomify/atomify) to manage our dependencies. Because angular-ra-newrelic and angular-ra-pageload use implicit annotation instead of inline array notation for injected dependencies, minifying the code breaks the app.

Would it be possible to use inline array annotation so that the module can be bundled and minified?

### PR DESCRIPTION
**Pull request by ashleahhill**
Fixes #1

### CODE REVIEW

**Comment by insaineyesay** [comment]
:+1:

**Comment by mrlannigan** [comment]
:+1:

**Comment by abeane** [comment]
Please approve!

**Comment by jsntv200** [comment]
Thanks for the feedback. We use ngAnnotate to add the dependencies so I've fixed the grunt task to the add the dependencies for the non minified version. We always rely on ngAnnotate rather than add all the dependencies in the source.

We always used the minified version (which has the dependencies injected) so never ran into the issue.

**Pull request closed without merging**
